<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="2721" started-at="2019-03-19T06:44:59Z" finished-at="2019-03-19T06:45:01Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="2721" started-at="2019-03-19T06:44:59Z" finished-at="2019-03-19T06:45:01Z">
      <class name="testNGListners.TestCases">
        <test-method status="PASS" signature="startReport(java.lang.String, java.lang.String)[pri:0, instance:testNGListners.TestCases@de0a01f]" name="startReport" is-config="true" duration-ms="1202" started-at="2019-03-19T12:14:59Z" finished-at="2019-03-19T12:15:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="FirstMethod()[pri:0, instance:testNGListners.TestCases@de0a01f]" name="FirstMethod" duration-ms="29" started-at="2019-03-19T12:15:00Z" finished-at="2019-03-19T12:15:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FirstMethod -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testNGListners.TestCases@de0a01f]" name="getResult" is-config="true" duration-ms="4" started-at="2019-03-19T12:15:00Z" finished-at="2019-03-19T12:15:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=FirstMethod status=SUCCESS method=TestCases.FirstMethod()[pri:0, instance:testNGListners.TestCases@de0a01f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="secondMethod()[pri:0, instance:testNGListners.TestCases@de0a01f]" name="secondMethod" duration-ms="4" started-at="2019-03-19T12:15:00Z" finished-at="2019-03-19T12:15:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testNGListners.TestCaseMethods.secondMethod(TestCaseMethods.java:47)
	at testNGListners.TestCases.secondMethod(TestCases.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondMethod -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testNGListners.TestCases@de0a01f]" name="getResult" is-config="true" duration-ms="40" started-at="2019-03-19T12:15:00Z" finished-at="2019-03-19T12:15:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=secondMethod status=FAILURE method=TestCases.secondMethod()[pri:0, instance:testNGListners.TestCases@de0a01f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testNGListners.TestCases@de0a01f]" name="tearDown" is-config="true" duration-ms="1398" started-at="2019-03-19T12:15:00Z" finished-at="2019-03-19T12:15:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testNGListners.TestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
